### ISSUE TITLE
No such function: spatialite_version

### ISSUE THREAD

**Issue by arthuragone** [romain974/qspatialite#35]
On first click on the plugin I got this error : 

> The SQL query seems to be invalid.

no such function: spatialite_version

The complete report 👍 

>IndexError: list index out of range 
Traceback (most recent call last):
  File "/Users/arthur/.qgis2/python/plugins/QspatiaLite/qspatialite.py", line 68, in run
    dlg = QspatiaLiteApp(self.iface)
  File "/Users/arthur/.qgis2/python/plugins/QspatiaLite/QspatiaLiteApp.py", line 80, in __init__
    self.changeDb(max(0,self.connections['idx']))
  File "/Users/arthur/.qgis2/python/plugins/QspatiaLite/QspatiaLiteApp.py", line 141, in changeDb
    self.db=Database(self.connections['path'][index])
  File "/Users/arthur/.qgis2/python/plugins/QspatiaLite/Classes/Database.py", line 20, in __init__
    self.version=self.executeQuery("select spatialite_version()")[1][0][0].strip()
IndexError: list index out of range

Version de Python : 2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] 
Version de QGIS : 2.18.2 Las Palmas, exported 
OsX 10.10.5

When using  Manage Database in QGIS, I got also the following error when clicking on "table" of a polygonal layer 

> no such function: GeometryType

**Comment by mrejani** [comment]
I've the same problem:


The SQL query seems to be invalid.
no such function: spatialite_version

Versione Python: 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224] 
Versione di QGIS: 2.18.17 Las Palmas, exported
